# Generated by Django 3.0.5 on 2020-05-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regi',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('prn', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
